blocks:
  ancient_debris:
    material: "ancient_debris"
    requirements:
      world: "world_nether"
      min-blocks-between-last: 4
      max-y: 25
      min-y: 8
    average-calculation:
      min-samples: 5
      max-samples: 10 # Oldest samples will be removed if the amount is higher than this value
      min-average-seconds: 30 # If a player has a lower average than this, it will be considered suspicious
